public class Product {
    private int productId;    // Auto-generated by the system
    private String name;
    private int stockQuantity;
    private double salePrice;

    public Product(String name, int stockQuantity, double salePrice) {
        this.name = name;
        this.stockQuantity = stockQuantity;
        this.salePrice = salePrice;
    }

    // Getter and setter for productId
    public int getProductId() {
        return productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    // Getter and setter for name
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // Getter and setter for stockQuantity
    public int getStockQuantity() {
        return stockQuantity;
    }

    public void setStockQuantity(int stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    // Method to adjust stock (decrease when an order is processed, increase when a shipment is received)
    public void adjustStock(int quantityChange) {
        this.stockQuantity += quantityChange;
    }

    // Getter and setter for salePrice
    public double getSalePrice() {
        return salePrice;
    }

    public void setSalePrice(double salePrice) {
        this.salePrice = salePrice;
    }

    // Method to display product information
    public String displayProductInfo() {
        return "Product ID: " + productId + ", Name: " + name + 
               ", Stock Quantity: " + stockQuantity + 
               ", Sale Price: $" + salePrice;
    }
}
